name: cellsegment
channels:
  - conda-forge
dependencies:
  - aom=3.5.0
  - appnope=0.1.3
  - asttokens=2.4.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.5
  - blosc=1.21.5
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.19.1
  - c-blosc2=2.10.2
  - ca-certificates=2023.7.22
  - cairo=1.16.0
  - certifi=2023.7.22
  - charls=2.4.2
  - charset-normalizer=3.2.0
  - click=8.1.7
  - cloudpickle=2.2.1
  - contourpy=1.1.1
  - cycler=0.11.0
  - cytoolz=0.12.2
  - dask-core=2023.9.2
  - dav1d=1.2.1
  - decorator=5.1.1
  - executing=1.2.0
  - expat=2.5.0
  - ffmpeg=6.0.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.42.1
  - freetype=2.12.1
  - fribidi=1.0.10
  - fsspec=2023.9.1
  - gettext=0.21.1
  - giflib=5.2.1
  - glib=2.78.0
  - glib-tools=2.78.0
  - gmp=6.2.1
  - gnutls=3.7.8
  - graphite2=1.3.13
  - gst-plugins-base=1.22.5
  - gstreamer=1.22.5
  - harfbuzz=7.3.0
  - hdf5=1.14.1
  - icu=73.2
  - idna=3.4
  - imagecodecs=2023.9.4
  - imageio=2.31.1
  - importlib-metadata=6.8.0
  - importlib_metadata=6.8.0
  - ipython=8.14.0
  - jasper=4.0.0
  - jedi=0.19.0
  - joblib=1.3.2
  - jxrlib=1.1
  - kiwisolver=1.4.5
  - krb5=1.21.2
  - lame=3.100
  - lazy_loader=0.3
  - lcms2=2.15
  - lerc=4.0.0
  - libaec=1.0.6
  - libass=0.17.1
  - libavif16=1.0.1
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang=15.0.7
  - libclang13=15.0.7
  - libcurl=8.3.0
  - libcxx=16.0.6
  - libdeflate=1.18
  - libedit=3.1.20191231
  - libev=4.33
  - libexpat=2.5.0
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - libglib=2.78.0
  - libiconv=1.17
  - libidn2=2.3.4
  - libjpeg-turbo=2.1.5.1
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm15=15.0.7
  - libnghttp2=1.52.0
  - libogg=1.3.4
  - libopenblas=0.3.24
  - libopencv=4.7.0
  - libopus=1.3.1
  - libpng=1.6.39
  - libpq=15.4
  - libprotobuf=3.21.12
  - libsqlite=3.43.0
  - libssh2=1.11.0
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libvorbis=1.3.7
  - libvpx=1.13.0
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxml2=2.11.5
  - libzlib=1.2.13
  - libzopfli=1.0.3
  - llvm-openmp=16.0.6
  - locket=1.0.0
  - lz4-c=1.9.4
  - matplotlib=3.7.1
  - matplotlib-base=3.7.1
  - matplotlib-inline=0.1.6
  - munkres=1.1.4
  - mysql-common=8.0.33
  - mysql-libs=8.0.33
  - ncurses=6.4
  - nettle=3.8.1
  - networkx=3.1
  - nspr=4.35
  - nss=3.92
  - numpy=1.25.0
  - opencv=4.7.0
  - openh264=2.3.1
  - openjpeg=2.5.0
  - openssl=3.1.2
  - p11-kit=0.24.1
  - packaging=23.1
  - pandas=2.0.3
  - parso=0.8.3
  - partd=1.4.0
  - pcre2=10.40
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=10.0.0
  - pip=23.2.1
  - pixman=0.40.0
  - platformdirs=3.10.0
  - ply=3.11
  - pooch=1.7.0
  - prompt-toolkit=3.0.39
  - prompt_toolkit=3.0.39
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - py-opencv=4.7.0
  - pygments=2.16.1
  - pyparsing=3.1.1
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pysocks=1.7.1
  - python=3.10.12
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - python_abi=3.10
  - pytz=2023.3.post1
  - pywavelets=1.4.1
  - pyyaml=6.0.1
  - qt-main=5.15.8
  - rav1e=0.6.6
  - readline=8.2
  - requests=2.31.0
  - scikit-image=0.20.0
  - scikit-learn=1.3.0
  - scipy=1.11.1
  - setuptools=68.2.2
  - sip=6.7.11
  - six=1.16.0
  - snappy=1.1.10
  - stack_data=0.6.2
  - svt-av1=1.7.0
  - threadpoolctl=3.2.0
  - tifffile=2023.8.30
  - tk=8.6.12
  - toml=0.10.2
  - tomli=2.0.1
  - toolz=0.12.0
  - tornado=6.3.3
  - traitlets=5.10.0
  - typing-extensions=4.7.1
  - typing_extensions=4.7.1
  - tzdata=2023c
  - unicodedata2=15.0.0
  - wcwidth=0.2.6
  - wheel=0.41.2
  - x264=1!164.3095
  - x265=3.5
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - yaml=0.2.5
  - zfp=1.0.0
  - zipp=3.16.2
  - zlib=1.2.13
  - zlib-ng=2.0.7
  - zstd=1.5.5
  - pip:
      - absl-py==1.4.0
      - antlr4-python3-runtime==4.9.3
      - anylabeling==0.3.3
      - black==23.7.0
      - cachetools==5.3.1
      - chardet==5.1.0
      - coloredlogs==15.0.1
      - colorlog==6.7.0
      - darkdetect==0.8.0
      - detectron2==0.6
      - filelock==3.12.2
      - fire==0.5.0
      - flatbuffers==23.5.26
      - fvcore==0.1.5.post20221221
      - google-auth==2.22.0
      - google-auth-oauthlib==1.0.0
      - grpcio==1.56.2
      - humanfriendly==10.0
      - hydra-core==1.3.2
      - imgviz==1.7.2
      - iopath==0.1.9
      - jinja2==3.1.2
      - jsonschema==4.18.2
      - jsonschema-specifications==2023.6.1
      - lxml==4.9.3
      - mapbox-earcut==1.0.1
      - markdown==3.4.4
      - markdown-it-py==3.0.0
      - markupsafe==2.1.3
      - mdurl==0.1.2
      - mpmath==1.3.0
      - mypy-extensions==1.0.0
      - natsort==8.4.0
      - oauthlib==3.2.2
      - omegaconf==2.3.0
      - onnx==1.13.1
      - onnx-simplifier==0.4.33
      - onnxruntime==1.14.1
      - opencv-python-headless==4.8.0.74
      - pathspec==0.11.1
      - portalocker==2.7.0
      - protobuf==3.20.3
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pybboxes==0.1.6
      - pycocotools==2.0.6
      - pycollada==0.7.2
      - pyglet==1.5.27
      - qimage2ndarray==1.10.0
      - referencing==0.29.1
      - requests-oauthlib==1.3.1
      - rich==13.5.2
      - rpds-py==0.8.10
      - rsa==4.9
      - rtree==1.0.1
      - sahi==0.11.14
      - segment-anything==1.0
      - svg-path==6.3
      - sympy==1.12
      - tabulate==0.9.0
      - tensorboard==2.13.0
      - tensorboard-data-server==0.7.1
      - termcolor==2.3.0
      - terminaltables==3.1.10
      - torch==2.0.1
      - torchvision==0.15.2
      - tqdm==4.65.0
      - trimesh==3.21.7
      - urllib3==1.26.16
      - werkzeug==2.3.6
      - xxhash==3.2.0
      - yacs==0.1.8
